### PR TITLE
Add Swift package index yml file

### PR DESCRIPTION
**Pull request by kimdv**
This PR will the spi.yml file, so Swift Package Index can build the documentation.

I was thinking of only adding this, and then in follow up PR's add more markdown files, so like documentation for rules and configuration can be found easily.

### CODE REVIEW

**Comment by kimdv** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
Thank you, Kim.

Could you address the failures? Looks like adding `.spi.yml` enabled the *Documentation check*, that’s why it’s reporting errors now.

**Comment by kimdv** [comment]
@ahoppen I think it is all fixed now

**Review by ahoppen — APPROVED** [review]
Thank you, Kim!

**Comment by kimdv** [comment]
@ahoppen I see it failed: https://swiftpackageindex.com/swiftlang/swift-format/builds

If I compare with [swift-syntax](https://swiftpackageindex.com/swiftlang/swift-syntax/builds) is don't pass the same parameters. 
Any idea on why o.O

**Comment by ahoppen** [comment]
This seems to be an issue with swiftpackageindex.com: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3558

**Pull request merged**
